Bug: 95952 - "An invalid request was made (missing required attribute: a)" exception when adding task in shared mailbox" Bug: 95948 - "Script Error: undefined is not a function" when you click to any shared mailbox folder"
95952:
- Error thrown when clicking onto a fully shared mailbox Task folder; The folder was a ZmSharedProxy, with no createQuery function defined.  Changed ZmSharedProxy to derive from ZmFolder.
- No account was being used when creating a task in the fully shared Task Folder.  The folder did not have an owner set; Its parent (shared mailbox system root) does.

95948:
- Error thrown when clicking onto a fully shared/accepted share folder; The folder is now handled as a ZmSharedProxy, with no createQuery function defined.  Changed ZmSharedProxy to derive from ZmFolder.

http://bugzilla.zimbra.com/show_bug.cgi?id=95952

Copied from Perforce
 Change: 525867