Bug: 101819 - Script Error: t.setText is not a function>> while expanding DL and pressing Escape key.
Desc:
Prior to 8.7 the movement across expanded DL throw arrow keys was not working.

This is the bug fixed that issue: https://bugzilla.zimbra.com/show_bug.cgi?id=98089

Today when we type any dl name in the address bar we see an "Expand" link.
Next when we click on it,  the DL gets expanded and the text in the InputAddressField changes to "Collapse".
Similarly when we press "Esc" key the text changes to "Expand".

The changing of text from "Expand" to "Collapse" and back to "Expand" is done in the function:
ZmAutocompleteListView.prototype._setExpandText

So far so good. Now we finally add the DL to the addresss bar  and  then click the "+" icon  to expand the DL. 
Next when press "Esc"  the method  "ZmAutocompleteListView.prototype._setExpandText", again gets called.
For this scenario, there is no "textCtrl.setText"  function as here textCtrl is the "ZmAddressBubble" and not "DwtText". Hence we get the error.

To fix the script error  issue, we add a check to see if the "setText" function is defined for the Dwtcontrol.

Note:
Apart from this I can also reproduce the bug: https://bugzilla.zimbra.com/show_bug.cgi?id=101820
The current fix does not fix the issue reported in bug: 101820.


Changeset:
ZmAutocompleteListView.js: Add a check to see if the "setText" function is defined for the Dwtcontrol

https://bugzilla.zimbra.com/show_bug.cgi?id=101819

Copied from Perforce
 Change: 559915